apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-back-deployment
  namespace: lhb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-back
  template:
    metadata:
      labels:
        app: board-back
    spec:
      containers:
        - name: board-back
          image: sole07/board-back:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: board-back-service
  namespace: lhb
spec:
  type: LoadBalancer
  selector:
    app: board-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080