pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sole07/board-back"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                sh 'chmod +x gradlew'
                sh './gradlew build -x test'
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE}:latest -f cicd/Dockerfile ."
                    sh "docker push ${DOCKER_IMAGE}:latest"
                }
            }
        }

        stage('K8S Deploy') {
            steps {

                sh 'kubectl apply -f cicd/backend.yml -n lhb'
                sh 'kubectl rollout restart deployment/board-back-deployment -n lhb'
            }
        }
    }
}